spring:
  profiles:
    active: local
aws:
  credential: E:\coltonsvc\.idea\credentials.properties
  region: ap-northeast-1
  bucket:
    url: https://{bucketName}.s3-{region}.amazonaws.com/
  download:
    home: /opt/colton/download